# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-02 13:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='appointment_times',
        ),
        migrations.DeleteModel(
            name='AppointmentTime',
        ),
    ]
