# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-02 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0002_auto_20161002_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='dr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HealthNet.Doctor', verbose_name='Doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='ptient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HealthNet.Patient', verbose_name='Patient'),
        ),
    ]
