# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-04 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0006_auto_20161004_1221'),
        ('HealthNet', '0006_auto_20161003_1431'),
    ]

    operations = [
    ]
