# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-05 06:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0009_auto_20161104_2256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Message'},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='reciever',
            new_name='receiver',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='endtime',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 5, 2, 37, 21, 646372)),
        ),
    ]
