# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-06 00:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0011_auto_20161105_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='healthnetfiles')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HealthNet.Doctor', verbose_name='Doctor')),
                ('ptient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HealthNet.Patient', verbose_name='Patient')),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='endtime',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 5, 21, 21, 5, 473605)),
        ),
    ]
