# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-07 00:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0012_auto_20161105_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='cur_issue',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='endtime',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 6, 20, 29, 53, 652620)),
        ),
    ]
