# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-08 18:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0014_auto_20161108_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='endtime',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 8, 14, 4, 14, 872075)),
        ),
    ]
