# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-07 22:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0014_auto_20161107_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='endtime',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 7, 18, 17, 23, 651483)),
        ),
    ]
