# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-08 19:12
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HealthNet', '0015_auto_20161107_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription', models.CharField(max_length=300, null=True)),
                ('createdOn', models.DateTimeField(default=datetime.datetime.now)),
                ('receive', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recieve', to=settings.AUTH_USER_MODEL)),
                ('send', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='send', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'prescription',
            },
        ),
        migrations.AlterField(
            model_name='appointment',
            name='endtime',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 8, 14, 42, 7, 434004)),
        ),
    ]
