# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-08 19:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0015_auto_20161108_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthfiles',
            old_name='ptient',
            new_name='patient',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='endtime',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 8, 14, 34, 45, 519490)),
        ),
    ]
