# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-08 21:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0016_auto_20161108_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthfiles',
            old_name='ptient',
            new_name='patient',
        ),
        migrations.AddField(
            model_name='healthfiles',
            name='canview',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='healthfiles',
            name='comment',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='endtime',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 8, 16, 57, 39, 928667)),
        ),
    ]
