# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-08 20:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0016_auto_20161108_1404'),
        ('HealthNet', '0016_auto_20161108_1412'),
    ]

    operations = [
    ]
