# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-08 21:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0017_auto_20161108_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='endtime',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 8, 16, 59, 3, 213826)),
        ),
    ]
