# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-08 20:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0017_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthfiles',
            name='comment',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='endtime',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 8, 16, 17, 6, 451081)),
        ),
    ]
