# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-08 21:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0018_auto_20161108_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthfiles',
            name='canview',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='endtime',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 8, 16, 43, 23, 635365)),
        ),
    ]
