# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-05 23:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0019_auto_20161108_1613'),
        ('HealthNet', '0020_auto_20161202_1500'),
    ]

    operations = [
    ]
